server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: lawyer-service
          uri: http://localhost:8083
          predicates:
            - Path=/lawyers/**

        - id: post-service
          uri: http://localhost:8084
          predicates:
            - Path=/posts/**

        - id: contract-service
          uri: http://localhost:8085
          predicates:
            - Path=/contracts/**

        - id: chat-service
          uri: http://localhost:8086
          predicates:
            - Path=/chat/**
